## R-Basic Syntax

In [2]:
myString <- "Hello, World!"
print(myString)

[1] "Hello, World!"


## Data Types

In [1]:
## Data types - Vectors

# Logical 

v <- TRUE
print(class(v))


# Numeric 

v <- 23.5
print(class(v))


# Integer

v <- 2L
print(class(v))


# Complex

v <- 3 + 2i
print(class(v))


# Character

v <- "TRUE"
print(class(v))


# Raw

v <- charToRaw("Hello")
print(class(v))

[1] "logical"
[1] "numeric"
[1] "integer"
[1] "complex"
[1] "character"
[1] "raw"


## Vectors

In [1]:
apple <- c('red', 'green', 'yellow')
print(apple)

print(class(apple))

[1] "red"    "green"  "yellow"
[1] "character"


## List

In [5]:
list1 <- list(c(2,5,3),21.3,sin)
print(list1)


[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")



## Matrics

In [6]:
M <- matrix(c('a','a','b','c','b','a'), nrow = 2, ncol = 3, byrow = TRUE)
print(M)

     [,1] [,2] [,3]
[1,] "a"  "a"  "b" 
[2,] "c"  "b"  "a" 


## Arrays

In [7]:
a <- array(c('green', 'yellow'), dim = c(3,3,2))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "yellow" "green" 
[2,] "yellow" "green"  "yellow"
[3,] "green"  "yellow" "green" 

, , 2

     [,1]     [,2]     [,3]    
[1,] "yellow" "green"  "yellow"
[2,] "green"  "yellow" "green" 
[3,] "yellow" "green"  "yellow"



## Factors

In [9]:
apple_colors <- c('green', 'green', 'yellow', 'red', 'red', 'green')

factor_apple <- factor(apple_colors)

print(factor_apple)

print(nlevels(factor_apple))

[1] green  green  yellow red    red    green 
Levels: green red yellow
[1] 3


## Data Frames

In [10]:
BMI <- data.frame(
    gender = c("Male", "Male", "Female"),
    height = c(152, 171.5, 165),
    weight = c(81,93,78),
    Age = c(42,38,26)
)


print(BMI)